name: PR build test
on:
  push:
  pull_request:

jobs:
  generate-meta:
    name: Generate metadata to build
    runs-on: ubuntu-latest
    outputs:
      linux-targets: ${{ steps.set-meta.outputs.linux-targets }}
    permissions:
      contents: read
    steps:
      - name: Checkout this ref
        uses: actions/checkout@v3

      - name: Extract the configuration from the JSON file
        # Read from the file and remove newline characters: https://stackoverflow.com/a/64627966
        id: set-meta
        run: |
          LINUX_TARGETS=$(cat "$JSON_FILE_NAME"|jq -c .linux_targets )
          echo "linux-targets=$LINUX_TARGETS"
          echo "linux-targets=$LINUX_TARGETS" >> $GITHUB_OUTPUT
        shell: bash
        env:
          JSON_FILE_NAME: ./build-config-staging.json

  lts-package-build-linux:
    needs:
      - generate-meta
    uses: ./.github/workflows/call-build-linux-packages.yaml
    strategy:
      fail-fast: true
      matrix:
        distro: [""]
        runner: ["ubuntu-latest"]
        include: ${{ fromJson(needs.generate-meta.outputs.linux-targets) }}
    with:
      distro: ${{ matrix.distro }}
      runner: ${{ matrix.runner }}